import type {Metadata} from 'next'
import './globals.css'
import Navbar from "@/app/nav/Navbar";
import ToasterProvider from "@/app/providers/ToasterProvider";
import SignalRProvider from "@/app/providers/SignalRProvider";

export const metadata: Metadata = {
	  title: 'Carsties',
	  description: 'Generated by Ali Shahbazi',
}

export default function RootLayout({
										 children,
								   }: {
	  children: React.ReactNode
}) {
	  return (
			<html lang="en">
			<body>
			<ToasterProvider />
			<Navbar/>
			<main className={'container mx-auto px-5 pt-10'}>
				  <SignalRProvider>
						{children}
				  </SignalRProvider>
			</main>
			</body>
			</html>
	  )
}
